In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
#Reading my test and train dataset

train = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\train.csv")

test = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\test.csv")

In [3]:
#I am going to use only the numerical variable for both the test and train dataset

numeric = ['int16','int64','int32','float64','float16','float32']

train = train.select_dtypes(include = numeric)

test = test.select_dtypes(include = numeric)

In [4]:
#Viewing my data


train.head()

Trainings_Attended  Year_of_birth  Last_performance_score  \
0                   2           1986                    12.5   
1                   2           1991                    12.5   
2                   2           1987                     7.5   
3                   3           1982                     2.5   
4                   3           1990                     7.5   

   Year_of_recruitment  Targets_met  Previous_Award  Training_score_average  \
0                 2011            1               0                      41   
1                 2015            0               0                      52   
2                 2012            0               0                      42   
3                 2009            0               0                      42   
4                 2012            0               0                      77   

   Promoted_or_Not  
0                0  
1                0  
2                0  
3                0  
4                0

In [5]:
# I am going to create a new colum called years of experience

for ind, row in train.iterrows():
    train.loc[ind,'Years_of_Experience'] = 2019 - row['Year_of_recruitment']

In [6]:
train.head()

Trainings_Attended  Year_of_birth  Last_performance_score  \
0                   2           1986                    12.5   
1                   2           1991                    12.5   
2                   2           1987                     7.5   
3                   3           1982                     2.5   
4                   3           1990                     7.5   

   Year_of_recruitment  Targets_met  Previous_Award  Training_score_average  \
0                 2011            1               0                      41   
1                 2015            0               0                      52   
2                 2012            0               0                      42   
3                 2009            0               0                      42   
4                 2012            0               0                      77   

   Promoted_or_Not  Years_of_Experience  
0                0                  8.0  
1                0                  4.0  
2                0                  7.0  
3                0                 10.0  
4                0                  7.0

In [7]:
#i did the same thing for age


for ind, row in train.iterrows():
    train.loc[ind,'Age'] = 2019 - row['Year_of_birth']

In [8]:
train.head()

Trainings_Attended  Year_of_birth  Last_performance_score  \
0                   2           1986                    12.5   
1                   2           1991                    12.5   
2                   2           1987                     7.5   
3                   3           1982                     2.5   
4                   3           1990                     7.5   

   Year_of_recruitment  Targets_met  Previous_Award  Training_score_average  \
0                 2011            1               0                      41   
1                 2015            0               0                      52   
2                 2012            0               0                      42   
3                 2009            0               0                      42   
4                 2012            0               0                      77   

   Promoted_or_Not  Years_of_Experience   Age  
0                0                  8.0  33.0  
1                0                  4.0  28.0  
2                0                  7.0  32.0  
3                0                 10.0  37.0  
4                0                  7.0  29.0

In [9]:
train.drop(columns=['Year_of_birth','Year_of_recruitment'],inplace=True)

In [10]:
train.head()

Trainings_Attended  Last_performance_score  Targets_met  Previous_Award  \
0                   2                    12.5            1               0   
1                   2                    12.5            0               0   
2                   2                     7.5            0               0   
3                   3                     2.5            0               0   
4                   3                     7.5            0               0   

   Training_score_average  Promoted_or_Not  Years_of_Experience   Age  
0                      41                0                  8.0  33.0  
1                      52                0                  4.0  28.0  
2                      42                0                  7.0  32.0  
3                      42                0                 10.0  37.0  
4                      77                0                  7.0  29.0

In [11]:
#doing the same thing for test data



In [12]:
for ind, row in test.iterrows():
    test.loc[ind,'Age'] = 2019 - row['Year_of_birth']

In [13]:
for ind, row in test.iterrows():
    test.loc[ind,'Years_of_Experience'] = 2019 - row['Year_of_recruitment']

In [14]:
test.drop(columns=['Year_of_birth','Year_of_recruitment'],inplace=True)

In [15]:
test.head()

Trainings_Attended  Last_performance_score  Targets_met  Previous_Award  \
0                   2                     7.5            0               0   
1                   2                     0.0            0               0   
2                   2                     7.5            0               0   
3                   2                     2.5            0               0   
4                   2                     7.5            1               0   

   Training_score_average   Age  Years_of_Experience  
0                      65  43.0                  2.0  
1                      69  28.0                  1.0  
2                      76  35.0                  7.0  
3                      52  35.0                 10.0  
4                      69  36.0                  5.0

In [16]:
#spliting my data into independent and dependent variables for modeling



X = train.drop('Promoted_or_Not', axis = 1)

y = train.Promoted_or_Not


In [17]:
# Using PCA- Principal Component Analysis, to do features selection

from sklearn.decomposition import PCA

pca = PCA(n_components=7)

X = pd.DataFrame(pca.fit_transform(X))

In [18]:
print(X.head())

           0         1         2         3         4         5         6
0 -14.320150  0.906180 -5.232832  0.985463 -0.215686  0.511906 -0.028925
1  -3.043412 -4.725570 -5.338265 -0.728435 -0.195729 -0.569452 -0.012208
2 -13.341108 -0.899755 -0.335739  1.328025 -0.215564 -0.312980 -0.001250
3 -13.693152  4.286973  5.048421  3.049335  0.750634 -0.015861  0.003759
4  21.747695 -2.045360 -0.102223  2.577321  0.705105 -0.321103 -0.023630


In [19]:
# Spliting my data test and train size

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size=0.3, random_state=42)

In [20]:
#using feature selection to select the most important features

import sklearn.feature_selection

select = sklearn.feature_selection.SelectKBest(k=7)

selected_features = select.fit(X_train,y_train)

indices_selected = selected_features.get_support(indices=True)

colnames_selected = [X.columns[i] for i in indices_selected]

X_train_selected = X_train[colnames_selected]
X_test_selected = X_test[colnames_selected]

In [21]:
colnames_selected

[0, 1, 2, 3, 4, 5, 6]

In [22]:
# Using Logistic Regression for Modelling


from sklearn.linear_model import LogisticRegression

lgr = LogisticRegression()

lgr.fit(X_train, y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [23]:
pred = lgr.predict(X_test)

In [24]:
from sklearn.metrics import f1_score

f1_score(pred, y_test)

0.09532710280373831

In [25]:
lgr.score(X_train,y_train)

0.9162129912745172

In [26]:
# let's try Random Forest

from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier, VotingClassifier
rf = RandomForestClassifier(n_estimators=20)
rf.fit(X_train,y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [27]:
rf.score(X_train,y_train)

0.9815795361324483

In [28]:
#Let Use Bagging for Modelling

bg = BaggingClassifier()
bg.fit(X_train,y_train)
bg.score(X_train,y_train)

0.9757998359310911

In [29]:
#Finally I am going to use a categorical voting for prediction

clf1 = LogisticRegression()
clf2 = RandomForestClassifier()
clf3 = BaggingClassifier()

In [30]:
ecf1 = VotingClassifier(estimators = [('lrg',clf1),('rf',clf2),('bg',clf3)], voting = 'hard')

In [31]:
ecf1 = ecf1.fit(X_train, y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [32]:
ecf1.score(X_train,y_train)

0.969199791185025

In [33]:
# f1 score

f1_score(pred, y_test)



0.09532710280373831

In [34]:
ecf1.fit(X,y)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


VotingClassifier(estimators=[('lrg', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)), ('rf', RandomF...imators=10, n_jobs=None, oob_score=False, random_state=None,
         verbose=0, warm_start=False))],
         flatten_transform=None, n_jobs=None, voting='hard', weights=None)

In [35]:
prediction = ecf1.predict(test).astype(int)

prediction

array([0, 0, 0, ..., 0, 0, 0])

In [36]:
# Working on Submission of my prediction

sample = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\sample_submission2.csv")

sub = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\test.csv")


In [37]:
sample.EmployeeNo = sub.EmployeeNo

sample.Promoted_or_Not = prediction

In [38]:
#Converting sample to csv

sample.to_csv('Prediction5.csv', index = False)

In [39]:
sample.head()

EmployeeNo  Promoted_or_Not
0  YAK/S/00005                0
1  YAK/S/00011                0
2  YAK/S/00015                0
3  YAK/S/00016                0
4  YAK/S/00017                0

In [40]:
#submiting prediction for random forest prediction

rf.score(X_train,y_train)

0.9815795361324483

In [41]:
rf.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [42]:
# f1 score
pred = rf.predict(X_test)
f1_score(pred, y_test)



0.8561797752808988

In [43]:
prediction = rf.predict(test).astype(int)

prediction

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
sample = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\sample_submission2.csv")

sub = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\test.csv")


In [45]:
sample.EmployeeNo = sub.EmployeeNo

sample.Promoted_or_Not = prediction

In [46]:
sample.to_csv('Prediction6.csv', index = False)

In [47]:
#Submitting Prediction for Bagging Classifier
bg.score(X_train,y_train)




0.9757998359310911

In [48]:
bg.fit(X,y)

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=1.0,
         n_estimators=10, n_jobs=None, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

In [49]:
pred = bg.predict(X_test)
f1_score(pred, y_test)



0.8237307472903594

In [50]:
prediction = bg.predict(test).astype(int)

prediction

array([0, 0, 0, ..., 0, 0, 0])

In [51]:
sample = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\sample_submission2.csv")

sub = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\test.csv")




sample.EmployeeNo = sub.EmployeeNo

sample.Promoted_or_Not = prediction

In [52]:


sample.to_csv('Prediction7.csv', index = False)

In [53]:
# Implementing Ada Boost

from sklearn.tree import DecisionTreeClassifier



In [54]:
adb = AdaBoostClassifier(DecisionTreeClassifier(), n_estimators = 5, learning_rate = 1)

adb.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1, n_estimators=5, random_state=None)

In [55]:
adb.score(X_train,y_train)

0.9845998955925125

In [75]:
# I want try Bagging Again

bg = BaggingClassifier(DecisionTreeClassifier(), max_samples = 0.7, max_features = 1, n_estimators = 20)

bg.fit(X_train, y_train)

bg.score(X_train, y_train)

0.9618912670594377

In [76]:
bg.fit(X,y)

pred = bg.predict(X_test)


prediction = bg.predict(test).astype(int)

prediction

array([0, 0, 0, ..., 0, 0, 0])

In [77]:
f1_score(pred, y_test)


0.6971877043819489

In [58]:
sample = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\sample_submission2.csv")

sub = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\test.csv")




sample.EmployeeNo = sub.EmployeeNo

sample.Promoted_or_Not = prediction

In [59]:
sample.to_csv('Prediction8.csv', index = False)

In [78]:
# Using Decision Tree Classifier


dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

dt.score(X_train, y_train)

0.9845998955925125

In [79]:
dt.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [80]:
pred = dt.predict(X_test)


prediction = dt.predict(test).astype(int)

prediction

# The Prediction seems to overfit

array([0, 1, 0, ..., 1, 0, 0])

In [81]:
f1_score(pred, y_test)

0.8734177215189873

In [63]:
from sklearn.svm import SVC

In [64]:
svm = SVC()

svm.fit(X_train, y_train)

svm.score(X_train, y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9273249310164815

In [65]:
svm.fit(X,y)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [66]:
#f1 score 

pred = svm.predict(X_test)
f1_score(pred, y_test)


0.2424242424242424

In [67]:
prediction = svm.predict(test).astype(int)

prediction


array([0, 0, 0, ..., 0, 0, 0])

In [68]:
sample = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\sample_submission2.csv")

sub = pd.read_csv(r"C:\Users\HP\Videos\Machine Learning\test.csv")




sample.EmployeeNo = sub.EmployeeNo

sample.Promoted_or_Not = prediction

In [69]:
sample.to_csv('Prediction9.csv', index = False)