In [5]:
import numpy as np

In [6]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[1]

1

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[0:5] = 10

In [12]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
sliced_array =arr[0:6]

sliced_array

array([0, 1, 2, 3, 4, 5])

In [16]:
sliced_array[:] = 22

In [17]:
sliced_array

array([22, 22, 22, 22, 22, 22])

In [18]:
arr

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

In [19]:
sliced1 = arr.copy()

In [20]:
sliced1

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

In [26]:
sliced1[0:6] =1,2,3,4,5,7

In [27]:
sliced1

array([ 1,  2,  3,  4,  5,  7,  6,  7,  8,  9, 10])

In [28]:
arr

array([22, 22, 22, 22, 22, 22,  6,  7,  8,  9, 10])

In [29]:
arr_2d =np.array([[2,4,6],[8,10,12],[14,16,18]])

In [30]:
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
arr_2d[0]

array([2, 4, 6])

In [32]:
arr_2d[:2,1:]

array([[ 4,  6],
       [10, 12]])

In [36]:
arr_2d[1][1]

10

In [37]:
arr_2d[2][1]

16

In [42]:
arr2d = np.zeros((10,10),dtype=int)

In [43]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [44]:
arr2d = np.zeros((10,10))

In [45]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
arr_length = arr2d.shape[1]

In [49]:
arr_length

10

In [56]:
for i in range(arr_length):
    arr2d[i]=1
    
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
arr2d[1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
arr2d[1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
arr2d[[1,2,3,4,5]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])