In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [2]:
dframe1 = DataFrame({'key':['X','Z','Y','Z','X','X'],'data_set':np.arange(6)})

In [3]:
dframe1

key  data_set
0   X         0
1   Z         1
2   Y         2
3   Z         3
4   X         4
5   X         5

In [4]:
dframe2 = DataFrame({'key':['Q','Y','Z'],'data_set_2':[1,2,3]})

In [5]:
dframe2

key  data_set_2
0   Q           1
1   Y           2
2   Z           3

In [6]:
pd.merge(dframe1,dframe2)

key  data_set  data_set_2
0   Z         1           3
1   Z         3           3
2   Y         2           2

In [7]:
pd.merge(dframe1,dframe2,on='key')

key  data_set  data_set_2
0   Z         1           3
1   Z         3           3
2   Y         2           2

In [8]:
pd.merge(dframe1,dframe2,on='key',how='left')

key  data_set  data_set_2
0   X         0         NaN
1   Z         1         3.0
2   Y         2         2.0
3   Z         3         3.0
4   X         4         NaN
5   X         5         NaN

In [9]:
pd.merge(dframe1,dframe2,on='key',how='right')

key  data_set  data_set_2
0   Z       1.0           3
1   Z       3.0           3
2   Y       2.0           2
3   Q       NaN           1

In [10]:
#to merge 2 dframes 

pd.merge(dframe1,dframe2,on='key',how='outer')

key  data_set  data_set_2
0   X       0.0         NaN
1   X       4.0         NaN
2   X       5.0         NaN
3   Z       1.0         3.0
4   Z       3.0         3.0
5   Y       2.0         2.0
6   Q       NaN         1.0

In [11]:
dframe3 = DataFrame({'key':['X','X','X','Y','Z','Z'],'data_set_3':
                    range(6)})

In [12]:
dframe4 = DataFrame({'key':['Y','Y','X','X','Z'],'data_set_4':range(5)})

In [13]:
dframe4

key  data_set_4
0   Y           0
1   Y           1
2   X           2
3   X           3
4   Z           4

In [14]:
pd.merge(dframe3,dframe4)

key  data_set_3  data_set_4
0   X           0           2
1   X           0           3
2   X           1           2
3   X           1           3
4   X           2           2
5   X           2           3
6   Y           3           0
7   Y           3           1
8   Z           4           4
9   Z           5           4

In [15]:
dframe3

key  data_set_3
0   X           0
1   X           1
2   X           2
3   Y           3
4   Z           4
5   Z           5

In [16]:
#merging with multiple keys

df_left = DataFrame({'key1':['SF','SF','LA'],
                    'key2':['one','two','one'],
                    'left_data':[10,20,30]})

In [17]:
df_right = DataFrame({'key1':['SF','SF','LA','LA'],'key2':['one',
                                                           'one','one','two'],'right_data':[40,50,60,70]})

In [18]:
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [19]:
#mergting 2 dataframes

pd.merge(df_right,df_left,on=['key1','key2'],how='outer')

key1 key2  right_data  left_data
0   SF  one        40.0       10.0
1   SF  one        50.0       10.0
2   LA  one        60.0       30.0
3   LA  two        70.0        NaN
4   SF  two         NaN       20.0

In [24]:
pd.merge(df_left,df_right,on='key1')

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

In [23]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [25]:
#merging on indexes

df_left = DataFrame({'key':['X','Y','Z','X','Y'],'data':range(5)})

In [26]:
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [29]:
df_right = DataFrame({'group_data':[10,20]},index=['X','Y'])

In [30]:
df_right

group_data
X          10
Y          20

In [32]:
pd.merge(df_left,df_right,left_on='key',right_index=True)

key  data  group_data
0   X     0          10
3   X     3          10
1   Y     1          20
4   Y     4          20

In [36]:
pd.merge(df_left,df_right,left_on='key',right_index=True)

key  data  group_data
0   X     0          10
3   X     3          10
1   Y     1          20
4   Y     4          20

In [41]:
df_left_hr = DataFrame({'key1':['SF','SF','SF','LA','LA'],
                       'key2':[10,20,30,20,30],
                       'data_set':np.arange(5.)})

In [42]:
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [44]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2),
                       index=[['LA','LA','SF','SF','SF'],
                             [20,10,10,10,20]],
                       columns=['col_1','col_2'])

In [45]:
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [46]:
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],
         right_index=True)

key1  key2  data_set  col_1  col_2
0   SF    10       0.0      4      5
0   SF    10       0.0      6      7
1   SF    20       1.0      8      9
3   LA    20       3.0      0      1

In [47]:
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [48]:
#shorter way of joining

In [49]:
df_left.join(df_right)

key  data  group_data
0   X     0         NaN
1   Y     1         NaN
2   Z     2         NaN
3   X     3         NaN
4   Y     4         NaN

In [50]:
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [51]:
df_right

group_data
X          10
Y          20

In [52]:
#concatenate

In [65]:
arr1 = np.arange(9).reshape(3,3)

In [55]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [74]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [76]:
ser1

T    0
U    1
V    2
dtype: int64

In [78]:
ser2

X    3
Y    4
dtype: int64

In [79]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [81]:
pd.concat([ser1,ser2],axis=1,sort=False)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [83]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [90]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [91]:
dframe1

X         Y         Z
0  0.206808 -2.249796  1.148449
1  0.259054  1.322762  0.980123
2  1.071078 -0.088194  0.829021
3  1.068265  0.820803 -0.271619

In [92]:
dframe2

Y         Q         X
0  0.420900 -0.840331  1.710400
1  1.254370 -0.256102 -2.074628
2 -1.975777  0.238395 -1.599502

In [93]:
pd.concat([dframe1,dframe2],sort=False)

X         Y         Z         Q
0  0.206808 -2.249796  1.148449       NaN
1  0.259054  1.322762  0.980123       NaN
2  1.071078 -0.088194  0.829021       NaN
3  1.068265  0.820803 -0.271619       NaN
0  1.710400  0.420900       NaN -0.840331
1 -2.074628  1.254370       NaN -0.256102
2 -1.599502 -1.975777       NaN  0.238395

In [89]:
pd.concat([dframe1,dframe2],sort=False,ignore_index=True)

Y         Q         X  key  data_set_2
0  0.720329 -0.270830 -0.230482  NaN         NaN
1  1.434061  1.372708  0.891830  NaN         NaN
2 -0.878303  1.302036  0.525942  NaN         NaN
3       NaN       NaN       NaN    Q         1.0
4       NaN       NaN       NaN    Y         2.0
5       NaN       NaN       NaN    Z         3.0